### ISSUE TITLE
Failing to send

### ISSUE THREAD

**Issue by hooperalex** [danikhan632/Auto-GPT-Messages-Plugin#3]
I was able to send an email. It was in a loop and I wanted to update the prompt.
I've rolled back, deployed a new instance from AutoGPT and it still gets stuck:

CRITICISM:  I need to ensure that I don't spend too much time on my response and get sidetracked from my other tasks.
NEXT ACTION:  COMMAND = send_email ARGUMENTS = {'to': 'xxx@me.com', 'subject': 'Re: Hi', 'body': 'Hi Ben,\n\nThanks for reaching out. How can I assist you today?\n\nBest regards,\n'}

**Comment by hooperalex** [comment]
Rebooting windows fixed it Doh!

**Comment by danikhan632** [comment]
Just to be clear as well, this is a Messages plugin, currently only supports iMessage however plan to support Whatsapp and Google/Android messages for web. There is already an email plugin but yeah it can't send emails
